spring:
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true

  application:
    name: keshuo-service
  profiles:
#    active: test
    #active: dev
    active: prod
logging:
  level:
    com.ks.keshuoservice.dao: debug