server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/keshuo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: abc123!@#

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml,mapper/*Mapper.xml
  type-aliases-package: com.ks.keshuoservice.entity.entity
  config-location: classpath:mybatis/mybatis-config.xml


logging:
  level:
    com.ks.keshuoservice.dao: debug

ceshi: 1
aff_sub2: http://ks.letianaso.com/api/interface/saveCallBackInfo
ip: 223.104.39.9

redirectUrl: http://ks.letianaso.com/inter/redirect